// <auto-generated />
namespace Phocalstream_Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CollectionStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollectionStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201210181443275_CollectionStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
