// <auto-generated />
namespace Phocalstream_Shared.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CameraSiteCountyFips : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CameraSiteCountyFips));
        
        string IMigrationMetadata.Id
        {
            get { return "201211052038402_CameraSiteCountyFips"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
